<div class="filters">
    <div class="form">
        <form action="" method="get">
            <select name="genre">
                <option selected disabled>All</option>
                <?php foreach ($genre as $value): ?>
                    <option value="<?php echo $value['name'] ?>"><?php echo $value['name'] ?></option>
                <?php endforeach; ?>
            </select>
            <select name="release_date">
                <option selected disabled>All</option>
                <?php foreach ($movies as $movie): ?>
                    <option value="<?php echo $movie->getYear(); ?>"><?php echo $movie->getYear(); ?></option>
                <?php endforeach; ?>
            </select>
            <input type="date" name="date">
            <select name="sort_by_release">
                <option selected disabled></option>
                <option value="ASC">Release Date Asc</option>
                <option value="DESC">Release Date Desc</option>
            </select>
            <input type="submit">
        </form>
    </div>
</div>
<?php foreach ($movies as $movie): ?>
    <a href="<?php echo "/movies/{$movie->getId()}/"; ?>">
        <div class="movie">
            <img class="movie-img" src="<?php echo $movie->getImage(); ?>"/>
            <h3><?php echo $movie->getName(); ?></h3>
            <h5><?php echo implode(', ', $movie->getGenres()); ?></h5>
        </div>
    </a>
<?php endforeach; ?>
